# Ansible Inventory for Project Sentinel Fleet Rollouts

[linux_servers]
bitbucket-node-1.internal.corp
bitbucket-node-2.internal.corp
artifactory-node-1.internal.corp
artifactory-node-2.internal.corp
jenkins-compute-1.internal.corp
teamcity-node-1.internal.corp

[windows_servers]
win-fortify-app-1.internal.corp
win-perfcenter-app-1.internal.corp

[all:vars]
ansible_user=svc_sentinel_deploy
ansible_connection=ssh
